### PR TITLE
Add -s option to read the schema from a supplied json file

### PR DESCRIPTION
**Pull request by eversinc33**
For me, the automatic schema introspection did not work I added a `-s` option to read the schema from a file, that can be created by manually introspecting.

grafik

### CODE REVIEW

**Review by gsmith257-cyber — APPROVED** [review]
Looks good. Thank you for adding this. Still trying to work out why some people are getting errors grabbing schemas using this.

**Comment by eversinc33** [comment]
With some tools, a missing trailing slash made the difference. Not sure why. I will investigate tomorrow if this is the case for this tool as well

**Comment by gsmith257-cyber** [comment]
I actually just pushed an update that should fix it. Try it out now and let me know.

**Comment by eversinc33** [comment]
Nice! WIll do

**Comment by eversinc33** [comment]
Your update did not fix the issue for me. However, adding a trailing slash did.

**Comment by gsmith257-cyber** [comment]
Can you send the URL you are using, of course change the domain name, because if it's something like site.com/api/graphql and your making it site.com/api/graphql/ then that's how the it's intended to work.

**Comment by eversinc33** [comment]
Yea, it was site.com/graphql and it's the trailing slash that was missing. As an easy and quick fix, I would suggest that you add a trailing slash to the target URL if the first fetching fails.

**Comment by gsmith257-cyber** [comment]
So I don't know exactly why but I've noticed with some endpoints, not just GraphQL, you need to call it with that trailing slash, even in the browser. I can defiantly add something real quick to add that trailing slash if the first request errors out.

**Pull request merged**
